services:
  - type: web
    name: Portalapp
    env: python
    buildCommand: apt-get update && apt-get install -y libmpv1
      pip install -r requirements.txt
    startCommand: flet run
    envVars:
      - key: PORT
        value: 10000