@startuml "Diagrama Entidad Relación - Productos"

skinparam linetype ortho
skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
}

entity "Producto" as producto {
    -id : int <<PK>>
    --
    *nombre : varchar(100)
    *precio : integer(10)
    *fecha : timestamp
    *stock : int
    descripcion : varchar(500)
    imagen_ruta : varchar(500)
    coste : integer(10)
}

@enduml