@startuml Casos de uso
left to right direction
actor Vendedor

rectangle "Portalapp" {
  package "Gestión de Productos" {
    usecase "Gestionar Inventario" as CU02
    usecase "Actualizar Stock" as CU02.1
    usecase "Eliminar Producto" as CU02.2
    usecase "Registrar Producto" as CU02.3
  }

  package "Gestión de Ventas" {
    usecase "Procesar Venta" as CU01
    usecase "Verificar Stock" as CU01.1
    usecase "Registrar Venta" as CU01.2
    usecase "Actualizar Stock" as CU01.3
    usecase "Generar Deuda" as CU01.4
  }

  package "Gestión de Reportes" {
    usecase "Generar Reportes" as CU04
    usecase "Generar Reporte de Ventas" as CU04.1
    usecase "Administrar Ventas" as CU04.3
    usecase "Generar Reporte de Deudas" as CU04.2
    usecase "Administrar Deudas" as CU04.4
  }

  package "Gestión de Deudas" {
    usecase "Administrar Deudas" as CU03
    usecase "Generar Deuda" as CU03.1
    usecase "Abonar Deuda" as CU03.2
    usecase "Crear Recordatorio" as CU03.3
  }

  ' Relaciones Gestión de Ventas
  Vendedor -- CU01
  CU01 ..> CU01.1 : <<include>>
  CU01 ..> CU01.2 : <<include>>
  CU01 ..> CU01.3 : <<include>>
  CU01.2 ..> CU01.4 : <<extend>>

  ' Relaciones Gestión de Productos
  Vendedor -- CU02
  CU02 ..> CU02.1 : <<include>>
  CU02 ..> CU02.2 : <<include>>
  CU02 ..> CU02.3 : <<include>>

  ' Relaciones Gestión de Deudas
  Vendedor -- CU03
  CU03 ..> CU03.1 : <<include>>
  CU03 ..> CU03.2 : <<include>>
  CU03 ..> CU03.3 : <<include>>

  ' Relaciones Gestión de Reportes
  Vendedor -- CU04
  CU04 ..> CU04.1 : <<include>>
  CU04 ..> CU04.2 : <<include>>

  CU04.1 ..> CU04.3 : <<extend>>
  CU04.2 ..> CU04.4 : <<extend>>
}

@enduml